export const name = 'dsh-web-access'
export { apply, Config, inject } from './plugin.ts'
export type { Config as PluginConfig } from './plugin.ts'
export { createEngine, executeFetchContent, executeGetSearchContent, executeSourceCheck, executeWebSearch } from './engine.ts'
export { search } from './gemini-search.ts'
export { getWebSearchConfigPath } from './utils.ts'
export { getSummaryGenerationDeadlineMs } from './config.ts'
